site_name: auth
site_description: Authentication application to be used in a microservice architecture.
repo_url: https://github.com/kiranmah/authservice
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/kiranmah">kiranmah</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
